### PR TITLE
Added VIS Chem Redux

### PR DESCRIPTION
**Pull request by darthbdaman**
Added rules for VIS Chem Redux to ensure it loads after Chem Redux

### CODE REVIEW

**Comment by Freso** [comment]
They do not have "chem redux.esp" as a master?

**Comment by darthbdaman** [comment]
No. I think their are multiple versions of chem redux with different names

**Comment by ghostsquad** [comment]
I can confirm at the vest least that this is the correct order that these esp's should be in. Any reason this PR cannot be resolved & merged (or closed)?

**Comment by Ortham** [comment]
I've manually merged it into the v0.8 branch in 2dd0b642ab4f6f5b73bd0242c8bbe7aec18779c9, and cherry-picked it into v0.10 in 966643e8af8ef15351674588eaca9a743291d14d.

*Edit: Reverted the v0.10 cherry-pick as it duplicates existing entries.*

**Pull request closed without merging**
