### PR TITLE
V0 10

### PR DESCRIPTION
**Pull request by Arthmoor**
Updadting exe versions for 1.10.50.

### CODE REVIEW

**Comment by Arthmoor** [comment]
Why does this say there are conflicts when my GitHub client told me no such thing when I made the pull request?

**Comment by Ortham** [comment]
Your local `v0.10` branch must be outdated - the "Files changed" tab shows the old versions as older than what's in the latest masterlist.

**Comment by Arthmoor** [comment]
Yes, but I don't understand why it thinks this is the case. The desktop client did not say there were any updates that needed to be synced and it let me do the changes and commit to my branch without incident. It only complained about the pull request. I thought Git was supposed to be better about this stuff than Subversion? :P

**Comment by Ortham** [comment]
The desktop client probably doesn't check upstream when committing to one of your own branches, because what to check is ambiguous, the relevant upstream branch is only decided when you make the PR.

In any case, I think I can work with this to merge it without erasing your authorship.

**Pull request merged**
