### PR TITLE
Danish translation of masterlist

### PR DESCRIPTION
**Pull request by Freso**
WIP Danish translation of masterlist. Putting up as PR so other people (if there should be anyone…) have a chance of reviewing it before getting merged into main masterlist.

### CODE REVIEW

**Comment by Freso** [comment]
I'm not at all sure how to translate `This file changes vanilla menu Form Lists. Consider using a compatible SKE Patch instead.` though.

@Sharlikran, you added this, as well as the Spanish translation, in 6830e95eaa81d2e7d986c0fe638d3be756b94296, so maybe you can clarify a bit how "vanilla menu Form Lists" should be parsed? (Or maybe I should pull myself together and figure out how to parse the Spanish properly. I feel like I'm falling way behind on my Spanish skillz. :/)

**Comment by Sharlikran** [comment]
Well I can try to explain but the last time it caused some confusion.  Maybe a few questions first will help, hopefully. :pray: 

1) Do you know that Bethesda has been changing Fallout4.esm to fit their needs with complete disregard to how it breaks existing mods?
2) Do you install Settlement mods that add new things you can build with or do you stick with the vanilla content that comes with the game and the DLC?
3) If you only use the vanilla content and the DLC do you use the Structures menu often?

I'm not going to ask about Form Lists, Overrides vs Conflicts, FormIDs, and use of xEdit because I think you know about all that and I'm not trying to be offensive.  I just want to be on the same page.

**Comment by Sharlikran** [comment]
Also, I don't use that for now after our conversation on the IRC channel.  So unless we can get on the same page and you can come up with a better suggestion then it might be best to remove &InsteadSKEPatch.

**Comment by Freso** [comment]
I've translated all the `common` and `global` messages, so I'm going to merge this into `v0.8` once tests are done… which they are now.

Thanks for your help and feedback, @Sharlikran!

**Pull request merged**
