### PR TITLE
Add official High Resolution Texture Pack

### PR DESCRIPTION
**Pull request by thurask**
Adds the official texture pack ESM (not that there's anything in it) right after the other official DLC.

### CODE REVIEW

**Comment by Freso** [comment]
Hm. It shouldn't go before the DLC? Does it contain textures from the DLCs as well?

**Comment by Ortham** [comment]
Is the metadata even necessary?

**Comment by thurask** [comment]
@Freso its only master is Fallout4.esm, so it should just be base game textures.

@WrinklyNinja maybe just the priority value then, if not the load order?

**Comment by Freso** [comment]
I decided to merge it after all. The suggested load order in the patch seems consistent with how it's reported in the community as well. I don't have the bandwidth to pull down a 55 GB mod right now, so I can't verify myself how `Fallout4.exe` actually orders it, and poking around in the .exe with a hexeditor did also not reveal any great revelations. If we figure out it should be sorted differently, we can fix the masterlist then.

**Pull request merged**
