### PR TITLE
Added Settlement Keywords and AWKCR

### PR DESCRIPTION
**Pull request by darthbdaman**
Added Settlement Keywords and Armor and Weapon Keywords Community
Resource priorities

### CODE REVIEW

**Comment by Ortham** [comment]
You know there's no difference between a priority of `-400998000` and one of `-1998000`, right? Other than that, looks good.

**Comment by darthbdaman** [comment]
Oh sorry. I didn't realize. I just copied over tags I had for the same stuff in NV

**Comment by Freso** [comment]
But don't both of these already have the master plugin flag set? What plugins got loaded before them that shouldn't get loaded before them? All the ones needing these that I've come across has had them set as masters, which makes LOOT sort them properly automatically.

**Comment by Ortham** [comment]
I'll defer to your judgement on this: if you think the priorities aren't necessary, feel free to revert the PR.

**Comment by Freso** [comment]
I'll let @darthbdaman respond, but my knee jerk reaction is that they aren't needed at this point to my knowledge.

**Comment by Freso** [comment]
I'll revert this. The reversion can be reverted once @darthbdaman gets back to us.

**Pull request merged**
